language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
before_script:
  - echo 'extension = mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
install:
  - composer install --no-interaction